version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    build:
        docker:
            - image: circleci/node:12.13.0
        working_directory: ~/EL_GAUCHO/api
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-
                      - v1-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-

            # - run: npm run test
    # deploy:
    #     machine:
    #         enabled: true
    #     steps:
    #         - add_ssh_keys:
    #               fingerprints:
    #                   - 'c3:c0:92:3c:04:15:65:d5:96:b1:2f:f1:fc:3a:4e:b7'
    #         - run:
    #               name: pull code and start service
    #               command: ssh -oStrictHostKeyChecking=no ssh root@103.81.87.65 -p gaucho-server "cd /EL_GAUCHO; git pull; cd api; npm install; pm2 restart gaucho"
workflows:
    my-flow:
        jobs:
            - build
            # - deploy
