module.exports.getBranch = [
    `branch_id`,
    `bussiness`,
    `store`,
    `creator`,
    'code',
    'name',
    'address',
    'ward',
    'district',
    'province',
    `_bussiness`,
    `_store`,
    `_creator`,
    `keyword`,
    `page`,
    `page_size`,
    `from_date`,
    `to_date`,
];

module.exports.addBranch = [
    'name',
    'phone',
    'latitude',
    'longtitude',
    'address',
    'ward',
    'district',
    'province',
    'store',
];
