module.exports.getBranch = [
    `branch_id`,
    `business_id`,
    `creator_id`,
    'code',
    'name',
    'address',
    'district',
    'province',
    `keyword`,
    `page`,
    `page_size`,
    `today`,
    `yesterday`,
    `this_week`,
    `last_week`,
    `this_month`,
    `last_month`,
    `this_year`,
    `last_year`,
    `from_date`,
    `to_date`,
];

module.exports.addBranch = [
    `name`,
    `logo`,
    `phone`,
    `email`,
    `fax`,
    `website`,
    `latitude`,
    `longtitude`,
    `address`,
    `district`,
    `province`,
];
