module.exports.getCustomer = [
    `customer_id`,
    `business_id`,
    `creator_id`,
    `code`,
    `type`,
    `phone`,
    `seach`,
    `page`,
    `page_size`,
    `today`,
    `yesterday`,
    `this_week`,
    `last_week`,
    `this_month`,
    `last_month`,
    `this_year`,
    `last_year`,
    `from_date`,
    `to_date`,
];

module.exports.addCustomer = [
    `phone`,
    `type`,
    `first_name`,
    `last_name`,
    `birthday`,
    `gender`,
    `address`,
    `district`,
    `province`,
    `balance`,
];
