module.exports.getSaleProduct = [
    `keyword`,
    `page`,
    `page_size`,
    `today`,
    `yesterday`,
    `this_week`,
    `last_week`,
    `this_month`,
    `last_month`,
    `this_year`,
    `last_year`,
    `from_date`,
    `to_date`,
    `branch`,
];
