module.exports.getUser = [
    `user_id`,
    `bussiness`,
    `username`,
    'branch',
    `_role`,
    `keyword`,
    `page`,
    `page_size`,
    `from_date`,
    `to_date`,
];

module.exports.addUser = [
    'username',
    'password',
    'role',
    'phone',
    'email',
    'avatar',
    'first_name',
    'last_name',
    'birthday',
    'address',
    'ward',
    'district',
    'province',
    'company_name',
    'company_website',
    'tax_code',
    'fax',
    `store`,
    'branch',
];
