let a = [...new Array(10)].map((item, index) => {
    return String(Math.random()).substr(2, 4);
});

let product = {
    business_id: '1',
    product_id: '1',
    sku: 'DSKU',
    barcode: '',
    name: 'DEMO PRODUCT',
    slug: 'demo-product',
    category_id: '1',
    supplier_id: '1',
    warranties: [
        {
            warranty_id: '1',
            business_id: '2',
            code: '1000001',
            name: 'BẢO HÀNH PHẦN MỀM',
            sub_name: 'baohanhphanmem',
            type: 'hỗ trợ toàn giá',
            sub_type: 'hotrotoangia',
            time: 6,
            description: '',
            create_date: '2021-09-04T18:42:20+07:00',
            creator_id: '2',
            active: true,
        },
    ],
    length: 0,
    width: 0,
    height: 0,
    weight: 0,
    unit: 'cái',
    description: 'mô tả sản phẩm',
    active: true,
    attributes: [
        {
            product_id: '1',
            attribute_id: '1',
            option: 'COLOR',
            values: ['WHITE'],
        },
        {
            product_id: '1',
            attribute_id: '2',
            option: 'SIZE',
            values: ['S', 'M'],
        },
    ],
    variants: [
        {
            product_id: '1',
            variant_id: '1',
            title: 'DEMO PRODUCT WHITE S',
            sku: 'DSKU-WHITE-S',
            option1: 'WHITE',
            option2: 'S',
            image: ['link'],
            supplier: 'NHÀ CUNG CẤP DEMO',
            import_price: 20,
            base_price: 40,
            sale_price: 100,
            locations: [
                {
                    id_location: '1',
                    variant_id: '1',
                    name: 'store',
                    available_stock_quantity: 100,
                    low_stock_quantity: 0,
                    out_stock_quantity: 0,
                    shipping_quantity: 0,
                    return_quantity: 0,
                    status_check: 10,
                    status_check_value: 10,
                    status: 'available_stock',
                },
                {
                    id_location: '1',
                    variant_id: '1',
                    name: 'branch',
                    available_stock_quantity: 0,
                    low_stock_quantity: 10,
                    out_stock_quantity: 0,
                    shipping_quantity: 0,
                    return_quantity: 0,
                    status_check: 10,
                    status_check_value: 20,
                    status: 'low_stock',
                },
            ],
            active: true,
        },
        {
            product_id: '1',
            variant_id: '1',
            title: 'DEMO PRODUCT WHITE M',
            sku: 'DSKU-WHITE-M',
            option1: 'WHITE',
            option2: 'M',
            image: ['link'],
            supplier: 'NHÀ CUNG CẤP DEMO',
            import_price: 20,
            base_price: 40,
            sale_price: 100,
            locations: [
                {
                    id_location: '1',
                    variant_id: '1',
                    name: 'store',
                    available_stock_quantity: 100,
                    low_stock_quantity: 0,
                    out_stock_quantity: 0,
                    shipping_quantity: 0,
                    return_quantity: 0,
                    status_check: 10,
                    status_check_value: 10,
                    status: 'available_stock',
                },
                {
                    id_location: '1',
                    variant_id: '1',
                    name: 'branch',
                    available_stock_quantity: 0,
                    low_stock_quantity: 10,
                    out_stock_quantity: 0,
                    shipping_quantity: 0,
                    return_quantity: 0,
                    status_check: 10,
                    status_check_value: 20,
                    status: 'low_stock',
                },
            ],
            active: true,
        },
    ],
};
